apiVersion: v1
kind: Pod
metadata:
  name: test
spec:
  containers:
    - name: my-app
      image: nginx
  affinity:
    nodeAffinity:
      preferredDuringSchedulingIgnoredDuringExecution:
        - weight: 100
          preference:
            matchExpressions:
              - key: eks.amazonaws.com/nodegroup
                operator: In
                values:
                  - test
