apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: interface
  name: interface
spec:
  replicas: 4
  selector:
    matchLabels:
      app: interface
  template:
    metadata:
      labels:
        app: interface
    spec:
      containers:
      - image: nginx
        name: nginx
        ports:
        - containerPort: 80
