apiVersion: v1
kind: Service
metadata:
  name: far-service
  namespace: default
spec:
  selector:
    WorkerType: fargate
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 80
      # nodePort: 30001

