apiVersion: apps/v1
kind: Deployment
metadata:
  name: fargate
  namespace: default
  labels:
    app: fargate
    WorkerType: fargate
spec:
  selector:
    matchLabels:
      WorkerType: fargate
  replicas: 3
  template:
    metadata:
      labels:
        WorkerType: fargate
    spec:
      # initContainers:
        # Init containers are exactly like regular containers, except:
          # - Init containers always run to completion.
          # - Each init container must complete successfully before the next one starts.
      containers:
      - name: fargate
        image: 134555352826.dkr.ecr.ap-northeast-2.amazonaws.com/zerotay/nginx:latest
        imagePullPolicy: IfNotPresent
        # resources:
        #   requests:
        #     cpu: 100m
        #     memory: 100Mi
        #   limits:
        #     cpu: 100m
        #     memory: 100Mi
        livenessProbe:
          tcpSocket:
            port: 80
          initialDelaySeconds: 5
          timeoutSeconds: 5
          successThreshold: 1
          failureThreshold: 3
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 5
          timeoutSeconds: 2
          successThreshold: 1
          failureThreshold: 3
          periodSeconds: 10
        ports:
        - containerPort: 80
          name: fargate
      restartPolicy: Always
